print("""Charecter set 1 alphabets""")
print("""Character set 2 number""")
print("""Character set 3 special symbols""")
print("""Character set 4 white space""")
print("""token 1 identifiers""")
print("""token 2 keywords""")
print("""token 3 constant """)
print("""token 4 special symboles""")
print("""token 5 white spaces""")
print("""token 6 operators""")
